export const FETCH_ARTS = "FETCH_ARTS";
export const ADD_WORK = "ADD_WORK";
export const FETCH_WORK_SUCCESS = "FETCH_WORK_SUCCESS";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const ADD_ITEM_TO_FAVORITE = "ADD_ITEM_TO_FAVORITE";
export const REMOVE_ITEM_FROM_FAVORITE = "REMOVE_ITEM_FROM_FAVORITE";

export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const FETCH_COMMENTS = " FETCH_COMMENTS";
